# Adding header to this file --- Update servers-----
- hosts: apt-servers
  sudo: true
  tasks:
    - name: Update package tool repo and cache
      apt: update_cache=yes force_apt_get=yes
    
    - name: Upgrade all packages
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed
      register: reboot_file
      stat: path=/var/run/reboot_required get_md5=no

    - name: Reboot Server
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_file.stat.exists == true
