#This playbbok will install vim,unzip,zip,wget  Excellent_Yeah
---
- hosts: webservers
  become: true
  vars:
      packages:
        - vim
        - unzip
        - zip
        - wget
        - git
      state: latest
  tasks:
    - name: Install vim,unzip,zip,wget
      yum:
      name: "{{ packages }}"
...
